# Generated by Django 4.1.7 on 2023-04-01 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('max_floor', models.IntegerField()),
                ('numbe_of_elevators', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevator_number', models.IntegerField()),
                ('is_operational', models.BooleanField(default=True)),
                ('current_floor', models.IntegerField(default=0)),
                ('is_door_open', models.BooleanField(default=False)),
                ('moving_status', models.IntegerField(choices=[(0, 'Idle'), (1, 'Moving Up'), (-1, 'Moving Down')], default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elevators', to='elev_app.building')),
            ],
        ),
    ]
