# Generated by Django 4.1.7 on 2023-04-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp',
        ),
    ]
