# Generated by Django 4.1.7 on 2023-04-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0002_delete_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='numbe_of_elevators',
            new_name='number_of_elevators',
        ),
    ]
