# Generated by Django 4.1.7 on 2023-04-01 12:55

from django.db import migrations, models
import django.db.models.deletion
import elev_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0003_rename_numbe_of_elevators_building_number_of_elevators'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_floor', models.IntegerField()),
                ('destination_floor', models.IntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elev_app.elevator')),
            ],
        ),
    ]
