# Generated by Django 4.1.7 on 2023-04-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elev_app', '0004_elevatorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorrequest',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='elev_app.elevator'),
        ),
    ]
